# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 11:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timentor', '0002_auto_20170102_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childtask',
            name='classification',
            field=models.CharField(max_length=256, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timentor.ParentTask', verbose_name='Task for'),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='task_name',
            field=models.CharField(max_length=256, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='task_no',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], validators=[django.core.validators.MaxValueValidator(10)], verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='time',
            field=models.CharField(max_length=3, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='time_end_hour',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(24)], verbose_name='To(Hour)'),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='time_end_min',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(60)], verbose_name='To(Min)'),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='time_ended_hour',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='time_ended_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='time_start_hour',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(24)], verbose_name='From(Hour)'),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='time_start_min',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(60)], verbose_name='From(Min)'),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='time_started_hour',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='time_started_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='task_date',
            field=models.CharField(default='2017/01/02', max_length=10, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='task_name',
            field=models.CharField(max_length=256, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='task_no',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], validators=[django.core.validators.MaxValueValidator(10)], verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time',
            field=models.CharField(max_length=3, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time_end_hour',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(24)], verbose_name='To(Hour)'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time_end_min',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(60)], verbose_name='To(Min)'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time_ended_hour',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time_ended_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time_start_hour',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(24)], verbose_name='From(Hour)'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time_start_min',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(60)], verbose_name='From(Min)'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time_started_hour',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time_started_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
    ]
