# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timentor', '0003_auto_20170102_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childtask',
            name='time_end_hour',
        ),
        migrations.RemoveField(
            model_name='childtask',
            name='time_end_min',
        ),
        migrations.RemoveField(
            model_name='childtask',
            name='time_ended_hour',
        ),
        migrations.RemoveField(
            model_name='childtask',
            name='time_ended_min',
        ),
        migrations.RemoveField(
            model_name='childtask',
            name='time_start_hour',
        ),
        migrations.RemoveField(
            model_name='childtask',
            name='time_start_min',
        ),
        migrations.RemoveField(
            model_name='childtask',
            name='time_started_hour',
        ),
        migrations.RemoveField(
            model_name='childtask',
            name='time_started_min',
        ),
        migrations.RemoveField(
            model_name='parenttask',
            name='time_end_hour',
        ),
        migrations.RemoveField(
            model_name='parenttask',
            name='time_end_min',
        ),
        migrations.RemoveField(
            model_name='parenttask',
            name='time_ended_hour',
        ),
        migrations.RemoveField(
            model_name='parenttask',
            name='time_ended_min',
        ),
        migrations.RemoveField(
            model_name='parenttask',
            name='time_start_hour',
        ),
        migrations.RemoveField(
            model_name='parenttask',
            name='time_start_min',
        ),
        migrations.RemoveField(
            model_name='parenttask',
            name='time_started_hour',
        ),
        migrations.RemoveField(
            model_name='parenttask',
            name='time_started_min',
        ),
        migrations.AddField(
            model_name='childtask',
            name='time_end',
            field=models.CharField(default='00:00', max_length=5, verbose_name='To(Min)'),
        ),
        migrations.AddField(
            model_name='childtask',
            name='time_ended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childtask',
            name='time_start',
            field=models.CharField(default='00:00', max_length=5, verbose_name='From(Hour)'),
        ),
        migrations.AddField(
            model_name='childtask',
            name='time_started',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parenttask',
            name='time_end',
            field=models.CharField(default='00:00', max_length=5, verbose_name='To(Min)'),
        ),
        migrations.AddField(
            model_name='parenttask',
            name='time_ended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parenttask',
            name='time_start',
            field=models.CharField(default='00:00', max_length=5, verbose_name='From(Hour)'),
        ),
        migrations.AddField(
            model_name='parenttask',
            name='time_started',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timentor.ParentTask', verbose_name='Task for'),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='time',
            field=models.CharField(choices=[(0.5, 0.5), (1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5), (6, 6), (7, 7)], max_length=3, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='task_date',
            field=models.CharField(default='2017/01/04', max_length=10, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time',
            field=models.CharField(choices=[(0.5, 0.5), (1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5), (6, 6), (7, 7)], max_length=3, verbose_name='Time'),
        ),
    ]
