# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timentor', '0006_auto_20170104_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childtask',
            name='time_end',
            field=models.TimeField(verbose_name='To(Min)'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time_end',
            field=models.TimeField(verbose_name='To(Min)'),
        ),
    ]
