# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timentor', '0010_auto_20170106_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childtask',
            name='time',
            field=models.CharField(choices=[('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=3, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='parenttask',
            name='time',
            field=models.CharField(choices=[('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=3, verbose_name='Time'),
        ),
    ]
